import { formatINR } from './utils.js';
import { renderLayout } from './layout.js';

export function renderLedger(data: any): string {
  const { 
    transactions, 
    businessProfile, 
    datePeriod, 
    reportHeading, 
    ledgerDetail,
    currentStats,
    currentOpeningBalance,
    currentClosingBalance
  } = data;
  
  if (!transactions) return renderLayout({ title: 'Ledger Report', businessProfile, content: '<p>No data provided.</p>' });
  
  let itemsHtml = '';
  transactions.forEach((t: any) => {
    itemsHtml += `
      <tr class="border-b border-slate-200">
        <td class="py-2 px-2 text-xs font-bold text-slate-800">${new Date(t.date).toLocaleDateString('en-IN')}</td>
        <td class="py-2 px-2 text-xs font-bold text-slate-800">${t.accountName || 'Unknown'}</td>
        <td class="py-2 px-2 text-xs text-slate-800 font-bold">${t.description}</td>
        <td class="py-2 px-2 text-right text-xs font-extrabold text-green-700">${t.type === 'Credit' ? formatINR(t.amount) : '-'}</td>
        <td class="py-2 px-2 text-right text-xs font-extrabold text-red-600">${t.type === 'Debit' ? formatINR(t.amount) : '-'}</td>
        <td class="py-2 px-2 text-right text-xs font-extrabold text-slate-900 bg-slate-50">${formatINR(t.runningBalance)}</td>
      </tr>
    `;
  });

  const content = `
    <div class="mb-4 flex justify-between items-end border-b border-slate-200 pb-2">
      <div>
        <p class="font-bold text-slate-800">${reportHeading}</p>
        <p class="text-xs text-slate-600 font-bold">${ledgerDetail}</p>
      </div>
      <div class="text-right">
        <p class="text-xs text-slate-600 font-bold">Period: ${datePeriod}</p>
      </div>
    </div>

    <!-- Summary Row -->
    <div class="flex justify-between items-center mb-4 text-xs font-bold bg-slate-50 p-2 border border-slate-200 rounded">
      <div>
        <span class="text-slate-500">Opening Balance:</span> 
        <span class="text-slate-900 ml-1">${formatINR(currentOpeningBalance)}</span>
      </div>
      <div>
        <span class="text-slate-500">Total Credit:</span> 
        <span class="text-green-700 ml-1">${formatINR(currentStats.credit)}</span>
      </div>
      <div>
        <span class="text-slate-500">Total Debit:</span> 
        <span class="text-red-600 ml-1">${formatINR(currentStats.debit)}</span>
      </div>
      <div>
        <span class="text-slate-500">Closing Balance:</span> 
        <span class="text-slate-900 ml-1">${formatINR(currentClosingBalance)}</span>
      </div>
    </div>

    <!-- Ledger Table -->
    <table class="w-full mb-6 border border-slate-200">
      <thead class="bg-slate-100 border-b border-slate-300">
        <tr>
          <th class="py-2 px-2 text-left text-xs font-bold text-slate-700 w-24">Date</th>
          <th class="py-2 px-2 text-left text-xs font-bold text-slate-700 w-32">Account</th>
          <th class="py-2 px-2 text-left text-xs font-bold text-slate-700">Description / Narration</th>
          <th class="py-2 px-2 text-right text-xs font-bold text-slate-700 w-24">Credit (In)</th>
          <th class="py-2 px-2 text-right text-xs font-bold text-slate-700 w-24">Debit (Out)</th>
          <th class="py-2 px-2 text-right text-xs font-bold text-slate-700 w-28">Balance</th>
        </tr>
      </thead>
      <tbody>
        ${transactions.length === 0 ? `
        <tr>
          <td colspan="6" class="py-8 text-center text-slate-400 italic font-medium">No transactions recorded for this period.</td>
        </tr>` : itemsHtml}
      </tbody>
      <tfoot class="bg-slate-100 border-t-2 border-slate-300 font-bold">
        <tr>
          <td colspan="3" class="py-2 px-2 text-right text-xs text-slate-700 uppercase">Period Totals:</td>
          <td class="py-2 px-2 text-right text-xs text-green-700">${formatINR(currentStats.credit)}</td>
          <td class="py-2 px-2 text-right text-xs text-red-600">${formatINR(currentStats.debit)}</td>
          <td class="py-2 px-2 text-right text-xs text-slate-900 bg-slate-200">${formatINR(currentClosingBalance)}</td>
        </tr>
      </tfoot>
    </table>

    <div class="mt-8 text-center text-[10px] text-slate-400 italic border-t border-dashed border-slate-200 pt-4">
      ${businessProfile.printFooter ? `<p class="font-bold text-slate-500 mb-1">${businessProfile.printFooter}</p>` : ''}
      <p>Period summary generated by ${businessProfile.companyName || "RupeeLedger Pro"} on ${new Date().toLocaleString('en-IN')}.</p>
    </div>
  `;

  return renderLayout({ 
    title: 'LEDGER REPORT', 
    businessProfile, 
    content,
    size: 'A4'
  });
}
